apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: httpserver-route
spec:
  http:
    - name: customer
      match:
        paths:
          - "/customer/*"
      backends:
        - serviceName: customer-service
          servicePort: 5000
          resolveGranularity: service
      authentication:
        enable: true
        type: keyAuth
    - name: product
      match:
        paths:
          - "/product/*"
      backends:
        - serviceName: product-service
          servicePort: 6000
          resolveGranularity: service
      authentication:
        enable: true
        type: keyAuth