apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: homelab-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /customer(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: customer-service
                port:
                  number: 8080
          - path: /product(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: product-service
                port:
                  number: 8080